apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: common-config
  namespace: common-config-app
spec:
  pathname: 'https://github.com/jxadro/mcmDemo.git'
  type: GitHub

---

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: common-config
  namespace: common-config-app
spec:
  selector:
    matchExpressions:
      - key: deployment
        operator: In
        values:
        - common-config
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription

---

apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: common-config-sub
  namespace: common-config-app
  labels:
    deployment: common-config
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: common-config
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel:  common-config-app/common-config
  placement:
    placementRef:
      kind: PlacementRule
      name: common-config

---

apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: common-config
  namespace: common-config-app
spec:
  clusterSelector:
    matchLabels:
      - {key: vendor, operator: In, values: ["OpenShift"]}
      
 
