apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: bookstore-kustomize-channel
  namespace: mcm-apps
spec:
  pathname: 'https://github.com/jxadro/mcmDemo.git'
  type: GitHub
  
---
  
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookstore-kustomize-app     
  namespace: mcm-apps
spec:
  selector:
    matchExpressions:
      - key: deployment  
        operator: In
        values:
        - bookstore-kustomize 
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
    
---

apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookstore-kustomize-frontal-cluster1
  namespace: bookstore-kustomize
  labels:
    deployment: bookstore-kustomize
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: frontal/overlays/cluster1
spec:
  channel:  mcm-apps/bookstore-kustomize-channel            
  placement: 
    placementRef: 
      kind: PlacementRule
      name: bookstore-kustomize-cluster1
      
---

apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: bookstore-kustomize-cluster1
  namespace: bookstore-kustomize
spec:
  clusterSelector:
    matchLabels:
      name: cluster1   
      
---

apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookstore-kustomize-frontal-clusterhub
  namespace: bookstore-kustomize
  labels:
    deployment: bookstore-kustomize
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: frontal/overlays/clusterhub
spec:
  channel:  mcm-apps/bookstore-kustomize-channel            
  placement: 
    placementRef: 
      kind: PlacementRule
      name: bookstore-kustomize-clusterhub
      
---

apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: bookstore-kustomize-clusterhub
  namespace: bookstore-kustomize
spec:
  clusterSelector:
    matchLabels:
      name: local-cluster       
    