apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: policies-channel
  namespace: secoperator-app
spec:
  pathname: 'https://github.com/jxadro/mcmDemo.git'
  type: GitHub

---

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: secop-app
  namespace: secoperator-app
spec:
  selector:
    matchExpressions:
      - key: deployment
        operator: In
        values:
        - secop-app
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription

---

apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: secop-sub
  namespace: secoperator-app
  labels:
    deployment: secop-app
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: secOp
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel:  secoperator-app/policies-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: policies-hub

---

apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: policies-hub
  namespace: secoperator-app
spec:
  clusterSelector:
    matchLabels:
      name: cluster1-ipi
