kind: Deployment
apiVersion: apps/v1
metadata:
  name: details
  namespace: bookstore-kustomize
spec:
  replicas: 2
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      hostNetwork: false
      containers:
      - name: details
        image: docker.io/jxadro/aiops_liberty_app:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - protocol: TCP
          containerPort: 9080
          name: http