kind: Service
apiVersion: v1
metadata:
  name: ratings
  namespace: bookstore-kustomize
  labels:
    app: ratings
spec:
  ports:
  - protocol: TCP
    name: http
    port: 9080
    targetPort: 9080
  selector:
    app: ratings
  sessionAffinity: None
  type: ClusterIP