kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-dep
  namespace: test-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-dep
  template:
    metadata:
      labels:
        app: demo-dep
    spec:
      hostNetwork: false
      containers:
      - name: details
        image: docker.io/jxadro/hellonode:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - protocol: TCP
          containerPort: 9080
          name: http
